#pragma once

// Auto-generated by scripts/translate-react.js
// Source: reactjs/packages/shared/ReactOwnerStackReset.js

#include "jsi/jsi.h"

namespace react {

namespace jsi = facebook::jsi;

void resetOwnerStackLimit(jsi::Runtime& runtime);

} // namespace react
